#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: artsready
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  app: artsready-staging
  config:
    BUNDLE_WITHOUT: "development:test"
    RACK_ENV: "staging"
