require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaymentVariablesController do

  # This should return the minimal set of attributes required to create a valid
  # PaymentVariable. As you add validations to PaymentVariable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaymentVariablesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all payment_variables as @payment_variables" do
      payment_variable = PaymentVariable.create! valid_attributes
      get :index, {}, valid_session
      assigns(:payment_variables).should eq([payment_variable])
    end
  end

  describe "GET show" do
    it "assigns the requested payment_variable as @payment_variable" do
      payment_variable = PaymentVariable.create! valid_attributes
      get :show, {:id => payment_variable.to_param}, valid_session
      assigns(:payment_variable).should eq(payment_variable)
    end
  end

  describe "GET new" do
    it "assigns a new payment_variable as @payment_variable" do
      get :new, {}, valid_session
      assigns(:payment_variable).should be_a_new(PaymentVariable)
    end
  end

  describe "GET edit" do
    it "assigns the requested payment_variable as @payment_variable" do
      payment_variable = PaymentVariable.create! valid_attributes
      get :edit, {:id => payment_variable.to_param}, valid_session
      assigns(:payment_variable).should eq(payment_variable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaymentVariable" do
        expect {
          post :create, {:payment_variable => valid_attributes}, valid_session
        }.to change(PaymentVariable, :count).by(1)
      end

      it "assigns a newly created payment_variable as @payment_variable" do
        post :create, {:payment_variable => valid_attributes}, valid_session
        assigns(:payment_variable).should be_a(PaymentVariable)
        assigns(:payment_variable).should be_persisted
      end

      it "redirects to the created payment_variable" do
        post :create, {:payment_variable => valid_attributes}, valid_session
        response.should redirect_to(PaymentVariable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payment_variable as @payment_variable" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentVariable.any_instance.stub(:save).and_return(false)
        post :create, {:payment_variable => {}}, valid_session
        assigns(:payment_variable).should be_a_new(PaymentVariable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentVariable.any_instance.stub(:save).and_return(false)
        post :create, {:payment_variable => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payment_variable" do
        payment_variable = PaymentVariable.create! valid_attributes
        # Assuming there are no other payment_variables in the database, this
        # specifies that the PaymentVariable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaymentVariable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => payment_variable.to_param, :payment_variable => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested payment_variable as @payment_variable" do
        payment_variable = PaymentVariable.create! valid_attributes
        put :update, {:id => payment_variable.to_param, :payment_variable => valid_attributes}, valid_session
        assigns(:payment_variable).should eq(payment_variable)
      end

      it "redirects to the payment_variable" do
        payment_variable = PaymentVariable.create! valid_attributes
        put :update, {:id => payment_variable.to_param, :payment_variable => valid_attributes}, valid_session
        response.should redirect_to(payment_variable)
      end
    end

    describe "with invalid params" do
      it "assigns the payment_variable as @payment_variable" do
        payment_variable = PaymentVariable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentVariable.any_instance.stub(:save).and_return(false)
        put :update, {:id => payment_variable.to_param, :payment_variable => {}}, valid_session
        assigns(:payment_variable).should eq(payment_variable)
      end

      it "re-renders the 'edit' template" do
        payment_variable = PaymentVariable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentVariable.any_instance.stub(:save).and_return(false)
        put :update, {:id => payment_variable.to_param, :payment_variable => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payment_variable" do
      payment_variable = PaymentVariable.create! valid_attributes
      expect {
        delete :destroy, {:id => payment_variable.to_param}, valid_session
      }.to change(PaymentVariable, :count).by(-1)
    end

    it "redirects to the payment_variables list" do
      payment_variable = PaymentVariable.create! valid_attributes
      delete :destroy, {:id => payment_variable.to_param}, valid_session
      response.should redirect_to(payment_variables_url)
    end
  end

end
